server:
  port: 8083
  servlet:
    context-path: /neo4j

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://db02.dev:3306/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
    #    username: root
    #    password: Dataadt123!
    url: jdbc:mysql://101.200.166.134:3308/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: LIUQQUERY
    password: LIUQQUERY156,
  redis:
    host: 192.168.131.110
    port: 8001
    timeout: 30000
    password:





logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.adtdata.neo4j.domain
  configuration:
    map-underscore-to-camel-case: true



csv:
  root-path: E:\temp
  step-size: 10000
  multithreading: true
  thread-count: 10
  head-path: E:\temp\head

importer:
  default-database: graph.db
  neo4j-path: F:\DevelopmentEnvironment\neo4j\neo4j-community-3.5.28
