server:
  port: 8083
  servlet:
    context-path: /neo4j

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db02.dev:3306/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Dataadt123!
#    url: jdbc:mysql://dbmaster.prod:3308/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: NEO4JIMPORT
#    password: Neo4JIMPOrT18,

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.adtdata.neo4j.domain
  configuration:
    map-underscore-to-camel-case: true

csv:
  root-path: 'E:\temp'
  step-size: 3000000
  multithreading: true
  thread-count: 3

importer:
  default-batch-config: 'E:\Idea-workspace\neo4j\batch-import\sample\batch.properties'
  default-database: 'E:\data\databases\graph.db'
