server:
  port: 13000
  servlet:
    context-path: /neo4jimport

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbmaster.prod:3308/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: NEO4JIMPORT
    password: Neo4JIMPOrT18,
  #    url: jdbc:mysql://101.200.166.134:3308/COMPANY?useUnicode=true&characterEncoding=utf8&useSSL=false
  #    username: LIUQQUERY
  #    password: LIUQQUERY156,
  redis:
    host: 192.168.131.110
    port: 8001
    timeout: 30000
    password:





logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.adtdata.neo4j.domain
  configuration:
    map-underscore-to-camel-case: true



csv:
  root-path: /nas03backup/neo4j/csv/data
  #  root-path: E:/temp
  step-size: 20000
  multithreading: true
  thread-count: 3
  #  head-path: E:/temp/head
  head-path: /nas03backup/neo4j/csv/data/head

importer:
  default-database: graph.db
  #  neo4j-path: F:\DevelopmentEnvironment\neo4j\neo4j-community-3.5.28
  neo4j-path: /nas03backup/neo4j/source/neo4j-community-3.5.6
